# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='unit_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
