# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderline_unit_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='total_price',
            new_name='line_price',
        ),
    ]
