# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20160930_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shop.Order'),
        ),
    ]
